apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: asdfkco/nginx-oss:nginxstore 
          ports:
            - containerPort: 80
      volumeMounts:
        - name: nginx-conf-d
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-conf-d
        configMap:
          name: nginx-plus-conf-d
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 1
