apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-plus-conf-d
  namespace: nginx
data:
  nginx.conf: |
      server {
        listen 80; 

        location / { 
          #root /usr/share/nginx/html/;
          #index index.html;
          proxy_pass http://192.168.201.28;
        }
      } 
