apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    configmap.reloader.stakater.com/reload: "nginx-plus-conf-d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: asdfkco/nginx-oss:nginxstore 
          ports:
            - containerPort: 80
          volumeMounts:
          - name: nginx-conf-d
            mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-conf-d
        configMap:
          name: nginx-plus-conf-d
