apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-d
  namespace: nginx
data:
  nginx.conf: |
      server {
        listen 80; 

        location / { 
          proxy_pass http://192.168.201.28;
        }
      } 
